# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ea93c1491b3e7b5e970ff65201685ad835147e1138b7c33962a7d4a83188cad91a8d22509cc8e9dbde0edf5a2dbdf94657a7b1eb783e8cdd614453c3be30194

test:
  secret_key_base: 279ca60afe6eea08c035c77ef91b8ea97da00d95907d1dc577e643cc2a8d06394b72b96effcaa2edc0ff61d0d252b1d82bcfdbca42ccb154c1b5ea6adcfd365d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
